# Generated by Django 4.2.6 on 2024-01-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsontool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgClassifierDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImagePath', models.CharField(max_length=255)),
            ],
        ),
    ]
