# Generated by Django 4.2.6 on 2024-01-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsontool', '0003_rename_imagepath_imgclassifierdisplay_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidClassifierDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=255)),
                ('video', models.FileField(default=None, max_length=250, null=True, upload_to='videos/')),
            ],
        ),
    ]
